### ISSUE TITLE
Problem with UrJTAG

### ISSUE THREAD

**Issue by AvatarBg111** [phdussud/pico-dirtyJtag#25]
Hello, I'm trying to debug a STM32F103 microcontroller using a Raspberry Pico with pico-DirtyJTAG firmware. I successfully flashed the Raspberry and tried connecting to it using openFPGALoader and I think it worked, because I got some IDs of the chip (IDCODE: 0x00000003, manufacturer: 0x001, part: 0x00 vers: 0x0). But openFPGALoader prompted me that the chip was an unknown device for it. So I decided to try out urjtag, but there is one step in the README.md file of your project that I cannot execute - "cable dirtyjtag". There is no "dirtyjtag" in the list of "cables". How do I add it, because I can't find any source that shows adding a "cable" configuration?

**Comment by jeanthom** [comment]
Hi,It seems like you are running a very old version of UrJTAG, or your build has dirtyjtag disabled. I'd recommend you rebuilding UrJTAG from source.Please be aware that UrJTAG is a horrible option for debugging modern ARM-based platforms. You'd better try the OpenOCD fork with DirtyJTAG support.JeanOn 31 May 2024, at 09:28, AvatarBg111 ***@***.***> wrote:﻿
Hello, I'm trying to debug a STM32F103 microcontroller using a Raspberry Pico with pico-DirtyJTAG firmware. I successfully flashed the Raspberry and tried connecting to it using openFPGALoader and I think it worked, because I got some IDs of the chip (IDCODE: 0x00000003, manufacturer: 0x001, part: 0x00 vers: 0x0). But openFPGALoader prompted me that the chip was an unknown device for it. So I decided to try out urjtag, but there is one step in the README.md file of your project that I cannot execute - "cable dirtyjtag". There is no "dirtyjtag" in the list of "cables". How do I add it, because I can't find any source that shows adding a "cable" configuration?

**Comment by AvatarBg111** [comment]
Ok, thanks for the help
